/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opbasicas;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gbs66
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private final String iconPath = "icon.png";
    
    public GUI() {
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource(iconPath));
        setIconImage(icono);
        
        areaPositiva.setLineWrap(true);
        areaPositiva.setWrapStyleWord(true);
        
        areaKleene.setLineWrap(true);
        areaKleene.setWrapStyleWord(true);
        
        areaSubcadenas.setLineWrap(true);
        areaSubcadenas.setWrapStyleWord(true);
        
        areaSufijos.setLineWrap(true);
        areaSufijos.setWrapStyleWord(true);
        
        areaPrefijos.setLineWrap(true);
        areaPrefijos.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        PanelCadenas = new javax.swing.JPanel();
        PanelTxtCadenas = new javax.swing.JPanel();
        txtCadena = new javax.swing.JTextField();
        lblCadena = new javax.swing.JLabel();
        PanelBtnCadenas = new javax.swing.JPanel();
        btnSaveCadenas = new javax.swing.JButton();
        btnClearCadenas = new javax.swing.JButton();
        btnOkCadenas = new javax.swing.JButton();
        PanelAreaCadenas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaSubcadenas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaPrefijos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaSufijos = new javax.swing.JTextArea();
        lblSubcadenas = new javax.swing.JLabel();
        lblPrefijos = new javax.swing.JLabel();
        lblSufijos = new javax.swing.JLabel();
        PanelLenguaje = new javax.swing.JPanel();
        PanelBtnLenguaje = new javax.swing.JPanel();
        btnSaveLenguaje = new javax.swing.JButton();
        btnClearLenguaje = new javax.swing.JButton();
        btnOkLenguaje = new javax.swing.JButton();
        PanelTxtAlfabeto = new javax.swing.JPanel();
        txtAlfabeto = new javax.swing.JTextField();
        lblAlfabeto = new javax.swing.JLabel();
        PanelAreaLenguaje = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaPositiva = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaKleene = new javax.swing.JTextArea();
        lblPositiva = new javax.swing.JLabel();
        lblKleene = new javax.swing.JLabel();
        PanelSpnLongMax = new javax.swing.JPanel();
        lblLongMax = new javax.swing.JLabel();
        spnLongMax = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpBasicas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        PanelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        PanelGeneral.setAlignmentX(0.0F);
        PanelGeneral.setAlignmentY(0.0F);
        PanelGeneral.setMaximumSize(new java.awt.Dimension(1280, 720));
        PanelGeneral.setMinimumSize(new java.awt.Dimension(1280, 720));
        PanelGeneral.setName(""); // NOI18N
        PanelGeneral.setPreferredSize(new java.awt.Dimension(1280, 720));

        PanelCadenas.setBackground(new java.awt.Color(51, 0, 51));
        PanelCadenas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Subcadenas, Pefijos y Sufijos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelCadenas.setAlignmentX(0.0F);
        PanelCadenas.setAlignmentY(0.0F);
        PanelCadenas.setMaximumSize(new java.awt.Dimension(1280, 357));
        PanelCadenas.setMinimumSize(new java.awt.Dimension(1280, 357));
        PanelCadenas.setPreferredSize(new java.awt.Dimension(1280, 357));

        PanelTxtCadenas.setBackground(new java.awt.Color(51, 0, 51));
        PanelTxtCadenas.setPreferredSize(new java.awt.Dimension(525, 60));

        txtCadena.setAlignmentX(0.0F);
        txtCadena.setAlignmentY(0.0F);
        txtCadena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCadena.setPreferredSize(new java.awt.Dimension(512, 25));

        lblCadena.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCadena.setForeground(new java.awt.Color(255, 255, 255));
        lblCadena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadena.setText("Cadena");
        lblCadena.setAlignmentY(0.0F);

        javax.swing.GroupLayout PanelTxtCadenasLayout = new javax.swing.GroupLayout(PanelTxtCadenas);
        PanelTxtCadenas.setLayout(PanelTxtCadenasLayout);
        PanelTxtCadenasLayout.setHorizontalGroup(
            PanelTxtCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTxtCadenasLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lblCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelTxtCadenasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTxtCadenasLayout.setVerticalGroup(
            PanelTxtCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTxtCadenasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBtnCadenas.setBackground(new java.awt.Color(51, 0, 51));
        PanelBtnCadenas.setMaximumSize(new java.awt.Dimension(204, 64));
        PanelBtnCadenas.setMinimumSize(new java.awt.Dimension(204, 64));
        PanelBtnCadenas.setPreferredSize(new java.awt.Dimension(204, 64));

        btnSaveCadenas.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveCadenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opbasicas/save.png"))); // NOI18N
        btnSaveCadenas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveCadenas.setMaximumSize(new java.awt.Dimension(64, 64));
        btnSaveCadenas.setMinimumSize(new java.awt.Dimension(64, 64));
        btnSaveCadenas.setPreferredSize(new java.awt.Dimension(64, 64));
        btnSaveCadenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCadenasActionPerformed(evt);
            }
        });

        btnClearCadenas.setBackground(new java.awt.Color(0, 0, 0));
        btnClearCadenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opbasicas/cross.png"))); // NOI18N
        btnClearCadenas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearCadenas.setMaximumSize(new java.awt.Dimension(64, 64));
        btnClearCadenas.setMinimumSize(new java.awt.Dimension(64, 64));
        btnClearCadenas.setPreferredSize(new java.awt.Dimension(64, 64));
        btnClearCadenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCadenasActionPerformed(evt);
            }
        });

        btnOkCadenas.setBackground(new java.awt.Color(0, 0, 0));
        btnOkCadenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opbasicas/check.png"))); // NOI18N
        btnOkCadenas.setActionCommand("btnOk");
        btnOkCadenas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOkCadenas.setMaximumSize(new java.awt.Dimension(64, 64));
        btnOkCadenas.setMinimumSize(new java.awt.Dimension(64, 64));
        btnOkCadenas.setPreferredSize(new java.awt.Dimension(64, 64));
        btnOkCadenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkCadenasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnCadenasLayout = new javax.swing.GroupLayout(PanelBtnCadenas);
        PanelBtnCadenas.setLayout(PanelBtnCadenasLayout);
        PanelBtnCadenasLayout.setHorizontalGroup(
            PanelBtnCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBtnCadenasLayout.createSequentialGroup()
                .addComponent(btnOkCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelBtnCadenasLayout.setVerticalGroup(
            PanelBtnCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnCadenasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelBtnCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveCadenas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearCadenas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkCadenas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanelAreaCadenas.setBackground(new java.awt.Color(51, 0, 51));
        PanelAreaCadenas.setMaximumSize(new java.awt.Dimension(1218, 234));
        PanelAreaCadenas.setMinimumSize(new java.awt.Dimension(1218, 234));
        PanelAreaCadenas.setPreferredSize(new java.awt.Dimension(1218, 234));

        areaSubcadenas.setColumns(20);
        areaSubcadenas.setRows(5);
        areaSubcadenas.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setViewportView(areaSubcadenas);

        areaPrefijos.setColumns(20);
        areaPrefijos.setRows(5);
        areaPrefijos.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane2.setViewportView(areaPrefijos);

        areaSufijos.setColumns(20);
        areaSufijos.setRows(5);
        areaSufijos.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane3.setViewportView(areaSufijos);

        lblSubcadenas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSubcadenas.setForeground(new java.awt.Color(255, 255, 255));
        lblSubcadenas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubcadenas.setText("Subcadenas");
        lblSubcadenas.setPreferredSize(new java.awt.Dimension(400, 16));

        lblPrefijos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPrefijos.setForeground(new java.awt.Color(255, 255, 255));
        lblPrefijos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrefijos.setText("Prefijos");
        lblPrefijos.setPreferredSize(new java.awt.Dimension(400, 16));

        lblSufijos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSufijos.setForeground(new java.awt.Color(255, 255, 255));
        lblSufijos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSufijos.setText("Sufijos");
        lblSufijos.setPreferredSize(new java.awt.Dimension(400, 16));

        javax.swing.GroupLayout PanelAreaCadenasLayout = new javax.swing.GroupLayout(PanelAreaCadenas);
        PanelAreaCadenas.setLayout(PanelAreaCadenasLayout);
        PanelAreaCadenasLayout.setHorizontalGroup(
            PanelAreaCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAreaCadenasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAreaCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAreaCadenasLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAreaCadenasLayout.createSequentialGroup()
                        .addComponent(lblSubcadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrefijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAreaCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSufijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelAreaCadenasLayout.setVerticalGroup(
            PanelAreaCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAreaCadenasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAreaCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubcadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrefijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSufijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAreaCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelCadenasLayout = new javax.swing.GroupLayout(PanelCadenas);
        PanelCadenas.setLayout(PanelCadenasLayout);
        PanelCadenasLayout.setHorizontalGroup(
            PanelCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadenasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelCadenasLayout.createSequentialGroup()
                        .addComponent(PanelTxtCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelBtnCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelAreaCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        PanelCadenasLayout.setVerticalGroup(
            PanelCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadenasLayout.createSequentialGroup()
                .addGroup(PanelCadenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTxtCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelBtnCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelAreaCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelLenguaje.setBackground(new java.awt.Color(51, 0, 51));
        PanelLenguaje.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "Cerradura de Kleene y Positiva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelLenguaje.setAlignmentX(0.0F);
        PanelLenguaje.setAlignmentY(0.0F);
        PanelLenguaje.setMaximumSize(new java.awt.Dimension(1280, 357));
        PanelLenguaje.setMinimumSize(new java.awt.Dimension(1280, 357));
        PanelLenguaje.setPreferredSize(new java.awt.Dimension(1280, 357));

        PanelBtnLenguaje.setBackground(new java.awt.Color(51, 0, 51));
        PanelBtnLenguaje.setMaximumSize(new java.awt.Dimension(204, 64));
        PanelBtnLenguaje.setMinimumSize(new java.awt.Dimension(204, 64));

        btnSaveLenguaje.setBackground(new java.awt.Color(0, 0, 0));
        btnSaveLenguaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opbasicas/save.png"))); // NOI18N
        btnSaveLenguaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveLenguaje.setMaximumSize(new java.awt.Dimension(64, 64));
        btnSaveLenguaje.setMinimumSize(new java.awt.Dimension(64, 64));
        btnSaveLenguaje.setPreferredSize(new java.awt.Dimension(64, 64));
        btnSaveLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveLenguajeActionPerformed(evt);
            }
        });

        btnClearLenguaje.setBackground(new java.awt.Color(0, 0, 0));
        btnClearLenguaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opbasicas/cross.png"))); // NOI18N
        btnClearLenguaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearLenguaje.setMaximumSize(new java.awt.Dimension(64, 64));
        btnClearLenguaje.setMinimumSize(new java.awt.Dimension(64, 64));
        btnClearLenguaje.setPreferredSize(new java.awt.Dimension(64, 64));
        btnClearLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLenguajeActionPerformed(evt);
            }
        });

        btnOkLenguaje.setBackground(new java.awt.Color(0, 0, 0));
        btnOkLenguaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opbasicas/check.png"))); // NOI18N
        btnOkLenguaje.setActionCommand("btnOk");
        btnOkLenguaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOkLenguaje.setMaximumSize(new java.awt.Dimension(64, 64));
        btnOkLenguaje.setMinimumSize(new java.awt.Dimension(64, 64));
        btnOkLenguaje.setPreferredSize(new java.awt.Dimension(64, 64));
        btnOkLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkLenguajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnLenguajeLayout = new javax.swing.GroupLayout(PanelBtnLenguaje);
        PanelBtnLenguaje.setLayout(PanelBtnLenguajeLayout);
        PanelBtnLenguajeLayout.setHorizontalGroup(
            PanelBtnLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBtnLenguajeLayout.createSequentialGroup()
                .addComponent(btnOkLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelBtnLenguajeLayout.setVerticalGroup(
            PanelBtnLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLenguajeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelBtnLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveLenguaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearLenguaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkLenguaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanelTxtAlfabeto.setBackground(new java.awt.Color(51, 0, 51));
        PanelTxtAlfabeto.setPreferredSize(new java.awt.Dimension(525, 60));

        txtAlfabeto.setAlignmentX(0.0F);
        txtAlfabeto.setAlignmentY(0.0F);
        txtAlfabeto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAlfabeto.setPreferredSize(new java.awt.Dimension(512, 25));

        lblAlfabeto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAlfabeto.setForeground(new java.awt.Color(255, 255, 255));
        lblAlfabeto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlfabeto.setText("Alfabeto");
        lblAlfabeto.setToolTipText("");
        lblAlfabeto.setAlignmentY(0.0F);

        javax.swing.GroupLayout PanelTxtAlfabetoLayout = new javax.swing.GroupLayout(PanelTxtAlfabeto);
        PanelTxtAlfabeto.setLayout(PanelTxtAlfabetoLayout);
        PanelTxtAlfabetoLayout.setHorizontalGroup(
            PanelTxtAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTxtAlfabetoLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lblAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelTxtAlfabetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTxtAlfabetoLayout.setVerticalGroup(
            PanelTxtAlfabetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTxtAlfabetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlfabeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAreaLenguaje.setBackground(new java.awt.Color(51, 0, 51));
        PanelAreaLenguaje.setMaximumSize(new java.awt.Dimension(1218, 234));
        PanelAreaLenguaje.setMinimumSize(new java.awt.Dimension(1218, 234));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(159, 87));

        areaPositiva.setColumns(20);
        areaPositiva.setRows(5);
        areaPositiva.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane4.setViewportView(areaPositiva);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setAutoscrolls(true);

        areaKleene.setColumns(20);
        areaKleene.setRows(5);
        areaKleene.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane5.setViewportView(areaKleene);

        lblPositiva.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPositiva.setForeground(new java.awt.Color(255, 255, 255));
        lblPositiva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPositiva.setText("Cerradura Positiva");
        lblPositiva.setPreferredSize(new java.awt.Dimension(400, 16));

        lblKleene.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKleene.setForeground(new java.awt.Color(255, 255, 255));
        lblKleene.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKleene.setText("Cerradura de Kleene");
        lblKleene.setPreferredSize(new java.awt.Dimension(400, 16));

        javax.swing.GroupLayout PanelAreaLenguajeLayout = new javax.swing.GroupLayout(PanelAreaLenguaje);
        PanelAreaLenguaje.setLayout(PanelAreaLenguajeLayout);
        PanelAreaLenguajeLayout.setHorizontalGroup(
            PanelAreaLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAreaLenguajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAreaLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAreaLenguajeLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAreaLenguajeLayout.createSequentialGroup()
                        .addComponent(lblPositiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKleene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAreaLenguajeLayout.setVerticalGroup(
            PanelAreaLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAreaLenguajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAreaLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPositiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKleene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAreaLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelSpnLongMax.setBackground(new java.awt.Color(51, 0, 51));
        PanelSpnLongMax.setPreferredSize(new java.awt.Dimension(300, 60));

        lblLongMax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLongMax.setForeground(new java.awt.Color(255, 255, 255));
        lblLongMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongMax.setText("Longitud Maxima");
        lblLongMax.setPreferredSize(new java.awt.Dimension(300, 16));

        spnLongMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spnLongMax.setPreferredSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout PanelSpnLongMaxLayout = new javax.swing.GroupLayout(PanelSpnLongMax);
        PanelSpnLongMax.setLayout(PanelSpnLongMaxLayout);
        PanelSpnLongMaxLayout.setHorizontalGroup(
            PanelSpnLongMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSpnLongMaxLayout.createSequentialGroup()
                .addComponent(lblLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSpnLongMaxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spnLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        PanelSpnLongMaxLayout.setVerticalGroup(
            PanelSpnLongMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSpnLongMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLenguajeLayout = new javax.swing.GroupLayout(PanelLenguaje);
        PanelLenguaje.setLayout(PanelLenguajeLayout);
        PanelLenguajeLayout.setHorizontalGroup(
            PanelLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLenguajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTxtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(PanelSpnLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(PanelBtnLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(PanelLenguajeLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(PanelAreaLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLenguajeLayout.setVerticalGroup(
            PanelLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLenguajeLayout.createSequentialGroup()
                .addGroup(PanelLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLenguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PanelTxtAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelBtnLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelSpnLongMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelAreaLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addComponent(PanelCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLenguaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkCadenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkCadenasActionPerformed
        if(txtCadena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Escribe una cadena valida.");
        } else {
            String cadena = txtCadena.getText();
            
            Set<String> subcadenas = Lenguaje.obtenerSubcadenas(cadena);
            Set<String> prefijos = Lenguaje.obtenerPrefijos(cadena);
            Set<String> sufijos = Lenguaje.obtenerSufijos(cadena);
            
            Set<String> pref = new TreeSet<>(prefijos);
            Set<String> subc = new TreeSet<>(subcadenas);
            Set<String> sufi = new TreeSet<>(sufijos);
            
            pref.remove("");
            subc.remove("");
            sufi.remove("");
            
            pref.add(" Ø");
            subc.add(" Ø");
            sufi.add(" Ø");
            
            areaSubcadenas.setText(subc.toString());
            areaPrefijos.setText(pref.toString());
            areaSufijos.setText(sufi.toString());
        }
    }//GEN-LAST:event_btnOkCadenasActionPerformed

    private void btnClearCadenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCadenasActionPerformed
        txtCadena.setText("");
        areaSubcadenas.setText("");
        areaPrefijos.setText("");
        areaSufijos.setText("");
    }//GEN-LAST:event_btnClearCadenasActionPerformed

    private void btnClearLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLenguajeActionPerformed
        areaPositiva.setText("");
        areaKleene.setText("");
        txtAlfabeto.setText("");
        spnLongMax.setValue((int) 0);
    }//GEN-LAST:event_btnClearLenguajeActionPerformed

    private void btnOkLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkLenguajeActionPerformed
        String alfabeto = txtAlfabeto.getText();
        if(alfabeto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Escribe un alfabeto valido.");
        } else {
            Lenguaje lenguaje = new Lenguaje(alfabeto);
            int longMax = (int) spnLongMax.getValue();
            if(longMax < 1) {
                JOptionPane.showMessageDialog(null, "Selecciona una longitud valida.");
            } else {
                Set<String> kleene = lenguaje.obtenerKleene(longMax);
                Set<String> positiva = lenguaje.obtenerPositiva(longMax);
                
                Set<String> kle = new TreeSet<>(kleene);
                Set<String> pos = new TreeSet<>(positiva);
                
                areaKleene.setText(kle.toString());
                areaPositiva.setText(pos.toString());
            }
        }
        
    }//GEN-LAST:event_btnOkLenguajeActionPerformed

    private void btnSaveLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveLenguajeActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar resultados");

        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File archivo = fileChooser.getSelectedFile();

            if (!archivo.getName().toLowerCase().endsWith(".txt")) {
                archivo = new File(archivo.getAbsolutePath() + ".txt");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {

                writer.write("RESULTADOS DE LA PRACTICA DE LENGUAJES\n");
                writer.write("=======================================\n\n");

                writer.write("CERRADURA POSITIVA (L+)\n");
                writer.write(areaPositiva.getText());
                writer.write("\n\n");

                writer.write("CERRADURA DE KLEENE (L*)\n");
                writer.write(areaKleene.getText());

                JOptionPane.showMessageDialog(this,
                        "Archivo guardado correctamente.");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al guardar el archivo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveLenguajeActionPerformed

    private void btnSaveCadenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCadenasActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar resultados");

        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File archivo = fileChooser.getSelectedFile();

            if (!archivo.getName().toLowerCase().endsWith(".txt")) {
                archivo = new File(archivo.getAbsolutePath() + ".txt");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivo))) {

                writer.write("RESULTADOS DE LA PRACTICA DE CADENAS\n");
                writer.write("=======================================\n\n");

                writer.write("SUBCADENAS\n");
                writer.write(areaSubcadenas.getText());
                writer.write("\n\n");
                
                writer.write("PREFIJOS\n");
                writer.write(areaPrefijos.getText());
                writer.write("\n\n");

                writer.write("SUFIJOS\n");
                writer.write(areaSufijos.getText());

                JOptionPane.showMessageDialog(this,
                        "Archivo guardado correctamente.");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al guardar el archivo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveCadenasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAreaCadenas;
    private javax.swing.JPanel PanelAreaLenguaje;
    private javax.swing.JPanel PanelBtnCadenas;
    private javax.swing.JPanel PanelBtnLenguaje;
    private javax.swing.JPanel PanelCadenas;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelLenguaje;
    private javax.swing.JPanel PanelSpnLongMax;
    private javax.swing.JPanel PanelTxtAlfabeto;
    private javax.swing.JPanel PanelTxtCadenas;
    private javax.swing.JTextArea areaKleene;
    private javax.swing.JTextArea areaPositiva;
    private javax.swing.JTextArea areaPrefijos;
    private javax.swing.JTextArea areaSubcadenas;
    private javax.swing.JTextArea areaSufijos;
    private javax.swing.JButton btnClearCadenas;
    private javax.swing.JButton btnClearLenguaje;
    private javax.swing.JButton btnOkCadenas;
    private javax.swing.JButton btnOkLenguaje;
    private javax.swing.JButton btnSaveCadenas;
    private javax.swing.JButton btnSaveLenguaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAlfabeto;
    private javax.swing.JLabel lblCadena;
    private javax.swing.JLabel lblKleene;
    private javax.swing.JLabel lblLongMax;
    private javax.swing.JLabel lblPositiva;
    private javax.swing.JLabel lblPrefijos;
    private javax.swing.JLabel lblSubcadenas;
    private javax.swing.JLabel lblSufijos;
    private javax.swing.JSpinner spnLongMax;
    private javax.swing.JTextField txtAlfabeto;
    private javax.swing.JTextField txtCadena;
    // End of variables declaration//GEN-END:variables
}
